# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
	desc "Push a new beta build to TestFlight"
	lane :upload do |options|
		type = nil
		increment_build_number
		case options[:type]
		when "p"
			type = "patch"
		when "m"
			type = "minor"
		when "mj"
			type = "major"
		end
		if type != nil 
			increment_version_number(
				bump_type: type # Automatically increment patch version number
			)
		end
		cocoapods
		build_app(workspace: "blockchainapp.xcworkspace", scheme: "blockchainapp")
		upload_to_testflight
	end
end
